version: "3"
services:
  ui:
    build:
      context: ui
      dockerfile: develop.Dockerfile
    volumes:
      - ./ui:/app
    working_dir: /app
    command: >
      sh -c '
        echo "installing packages..."
        npm install
        echo "install completed!"
        npm start
      '
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - REACT_APP_GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - REACT_APP_BACKEND_BASEURL=http://localhost:8000
  api:
    build:
      context: api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    environment:
      - PG_HOST=db
      - PG_DATABASE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - STAGE=develop
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    entrypoint:
      - "/usr/local/bin/wait-for-it.sh"
      - "db:5432"
      - "-t"
      - "60"
      - "--"
    command:
      - "uvicorn"
      - "main:app"
      - "--reload"
      - "--host"
      - "0.0.0.0"
    depends_on:
      - db
  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
