version: "3"
services:
  ui:
    build:
      context: ui
      dockerfile: develop.Dockerfile
    volumes:
      - ./ui:/app
    working_dir: /app
    command: >
      sh -c '
        echo "installing packages..."
        npm install
        echo "install completed!"
        npm start
      '
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file:
      - .env
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
