version: "3"
services:
  ui:
    build:
      context: ui
      dockerfile: develop.Dockerfile
    volumes:
      - ./ui:/app
    working_dir: /app
    command: >
      sh -c '
        echo "installing packages..."
        npm install
        echo "install completed!"
        npm start
      '
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - REACT_APP_GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - REACT_APP_BACKEND_BASEURL=http://api:8000
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    env_file:
      - .env
